### ISSUE TITLE
ImportIt does not preserve Unicode correctly

### ISSUE THREAD

**Issue by quark-zju** [facebook/fbshipit#156]
Importing https://github.com/facebook/sapling/pull/573 replaces the "🐛" in commit title with "�":

    [sapling][PR] �(chg): don't crash when user has more than 16 groups on macOS

and it seems various Unicode characters were not handled properly. For example,  "👍🏻" got imported as "👍�", and the author name "Max 👨🏽‍💻 Coplan" was imported as "Max 👨�‍💻 Coplan".

**Comment by bigfootjon** [comment]
Hey @quark-zju, this is actually not a problem with ImportIt *itself* this is a problem with our internal integrations that use ImportIt.

Since you're an employee, please report these issues on Workplace in the future and we can fix the OSS version if it's appropriate, but this is much more rare than bugs in the integrations with Phabricator.
