### ISSUE TITLE
Import Bot?

### ISSUE THREAD

**Issue by skevy** [facebook/fbshipit#17]
So, we have our internal monorepo syncing out to our different OSS projects -- yay! It's working great.

Now, the question of course is how do we accept PR's? It seems to be that most, if not all, of the fbshipit tooling could be used to build functionality like "@facebook-github-bot import". 

I'm curious about two things:

1) is the fbshipit code used internally to build the import/shipit bots?

2) Do you have any thoughts on how we might handle the case where we've moved files from an internal `__github__` folder into the root directory of the external repo during the outward sync, but on the inward sync those files need to be reconciled back to their proper place internally? An example of this in fb OSS seems like it would be the Relay repo. There's a moveDirectories filter that does `self::RELAY_ROOT.'/__github__/' => ''`. What way have you guys found to reconcile that when doing an import and generating a diff for Phabricator?

Curious to hear your thoughts. I want to build this! Manually building patches from PR's is for the birds :-)

Thanks!

/cc @fredemmott

**Comment by fredemmott** [comment]
1. At the moment, it's an entirely separate system, though we'd like to change this.

2. Some projects explicitly list the files, though the most common approach is probably manually applying these patches.

**Comment by chrisui** [comment]
I too am exploring how we can use fbshipit to sync internal projects from our private monorepo to public open source repos. (It seems a bit odd to have such a one-way tool atm but maybe I'm missing the point!)

I was wondering if, since fbshipit seems to have first-class support for writing to git & github, both of my repos live within github (they do - one private, the other public) I could theoretically have two shipit scripts which independently sync each way?

Would fbshipit be able to detect the, potentially interleaving changes? We could even avoid that problem by always running both scripts *together* (in some "sync" event) so on each side you collect changes since last sync and then apply diff in each direction.

@fredemmott @skevy

**Comment by fredemmott** [comment]
ShipIt does not support two-way sync, and it's not something we're particularly likely to work on; a single source of truth simplifies a huge number of problems.

That said, if you make it possible to change the tracking line added to commit messages and use a different one for each direction, skip if one's already present for the direction you're already going in, it will basically work - but it would probably be extremely time-consuming to debug and fix if the sync breaks in one direction only at some point and you keep pushing out patches in the other.

That said, it would be reasonable to use this approach if pull requests are merged to the internal repo instead of trying to have a true two-way-sync, i.e:

![screen shot 2016-09-01 at 10 41 37 am](https://cloud.githubusercontent.com/assets/360927/18177819/ad19bfc8-7030-11e6-8023-6a2ead63f5e4.png)

Pull requests could either be directly pushed by shipit to your internal repo (assuming it's Git or you send a PR for #1 :p):

 - have new shipit script with github as source, internal repo as dest
 - run shipit with --source-branch=pull/PR_NUMBER/head (https://help.github.com/articles/checking-out-pull-requests-locally/) and either:
   - do the differing identifier lines mentioned above
   - run with --skip-push, and with some other script, export the patch, amend it to remove the identifier, and land to your internal repo as normally
 - you'll want your filter function, an additional phase, or a separate script to add 'fixes #nnnn' to the commit message so that github closes the PR when it lands

**Comment by sdwilsh** [comment]
I'm actively working on this internally as we speak.  Expect the bulk of the code to land today or tomorrow.

**Comment by sdwilsh** [comment]
Commits that have already landed:
* https://github.com/facebook/fbshipit/commit/0b11437cb5c85368feac836bef009ded90ae38b8
* https://github.com/facebook/fbshipit/commit/c91a1d827229a52fe743452d6bbca703a41acfd4
* https://github.com/facebook/fbshipit/commit/8930077fd4f256ba598f254bf16dbdf4dabe8e83
